### ISSUE TITLE
Práctica 5

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JoseABCruz#3]
[Practica 5.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JoseABCruz/files/8309792/Practica.5.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
